@echo off
echo Running migrations in order...

echo 1. Running setup extensions...
node run-migration.js supabase/migrations/20250211_setup_extensions.sql

echo 2. Running clinical guidelines migration...
node run-migration.js supabase/migrations/20250216_create_clinical_guidelines.sql

echo 3. Running treatment algorithms migration...
node run-migration.js supabase/migrations/20250212_create_treatment_algorithms.sql

echo 4. Running evidence library migration...
node run-migration.js supabase/migrations/20250216_create_evidence_library.sql

echo 5. Running best practices migration...
node run-migration.js supabase/migrations/20250216_create_best_practices.sql

echo 6. Running oncology medications migration...
node run-migration.js supabase/migrations/20250223_create_oncology_medications.sql

echo All migrations completed.